server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB # 서블릿 multipart 관련 최대 파일 크기 설정, 예시 값: 100MB
      max-request-size: 100MB # 서블릿 multipart 관련 최대 요청 크기 설정, 예시 값: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: local
  data:
    web:
      pageable:
        default-page-size: 30 # paging 관련 기본 페이지 수 설정, 예시 값: 30
        max-page-size: 300 # paging 관련 최대 페이지 수 설정, 예시 값: 300
        one-indexed-parameters: true
        page-parameter: page
  jackson:
    property-naming-strategy: SNAKE_CASE # 응답 json 형식 자동 snake_case 화

extends: # 기타 설정하고 싶은 외부 환경변수 등
  jwt:
    secret-key: ${JWT_SECRET_KEY}
